import TGLExt.Commutant
import TGLExt.LeftRight
import TGLExt.FiniteTomita
import TGLExt.ModularFlow
import TGLExt.CondExpect
import TGLExt.PPIndex
import TGLExt.MarkovTower
import TGLExt.Bicommutant
import TGLExt.SMatrix
import TGLExt.Cocycle
import TGLExt.Ergodicity
import TGLExt.FiniteCrossedProduct
import TGLExt.GlobalLiftLadder
import TGLExt.CornerFamily
import TGLExt.BisognanoWichmann
import TGLExt.GravitonPolarization
import TGLExt.GeometryFluctuation
import TGLExt.PageInformation
import TGLExt.ModularFirstLaw
import TGLExt.RGStability
import TGLExt.VariationalInhabitant
import TGLExt.GNSBridge
import TGLExt.FiniteGNSNoCompletion
import TGLExt.TransportWitness
import TGLExt.CovariantCorner
import TGLExt.HilbertHome
import TGLExt.PsiEmergence
import TGLExt.AbsoluteOne
import TGLExt.ContinuousModularZero
import TGLExt.MinimalSolder
import TGLExt.NoFullWitness
import TGLExt.Solder4D
import TGLExt.LocalBreuerGap
import TGLExt.SusyRelativeGap
import TGLExt.EmergenceTriad
import TGLExt.TriadMaster
import TGLExt.LinearizedSpin2
import TGLExt.SemifiniteSeed
import TGLExt.DimensionTrace
import TGLExt.ThreeLocksCorner
import TGLExt.SemifiniteLattice
import TGLExt.ClosedLattice
import TGLExt.InvariantProjection
import TGLExt.BicommutantSkeleton
import TGLExt.SpectralReduction
import TGLExt.WitnessSeed
import TGLExt.ExactWitness
import TGLExt.WordExistence
import TGLExt.InfiniteWord
import TGLExt.HilbertInhabitant
import TGLExt.AQFTCoreInhabitant
import TGLExt.ConcreteFourFrame
import TGLExt.TheMasterFires
import TGLExt.ClosureCertificate
import TGLExt.ProgrammerRule
import TGLExt.IsotoneNet
import TGLExt.IdealLimit
import TGLExt.BenchCertificate
import TGLExt.StrongFrame
import TGLExt.WitnessV2
import TGLExt.NumberOperator
import TGLExt.NumberSelfAdjoint
import TGLExt.TailNet
import TGLExt.StrongAssembly
import TGLExt.SolderField
import TGLExt.FirstCurvature
import TGLExt.AnsatzEinstein
import TGLExt.FallenLight
import TGLExt.SolvedEquation
import TGLExt.ReducedEmergence
import TGLExt.GeometricWitness
import TGLExt.GravitonReading
import TGLExt.ContinuumShards
import TGLExt.EmergentEinstein
import TGLExt.PoincareGroup
import TGLExt.PoincareWitness
import TGLExt.RegularRep
import TGLExt.TracelessAlgebra
import TGLExt.SemifiniteWeight
import TGLExt.FusedWitness
import TGLExt.PowersLadder
import TGLExt.MixedLadder
import TGLExt.TheNameIsTheGeneratingGroup
import TGLExt.TheMarkIsNotATypeMark
import TGLExt.TheVerbalCoupling
import TGLExt.TheDammingByExpansion
import TGLExt.TheDischargedOath
import TGLExt.TheOathOnTheTower
import TGLExt.TheImportedExpectation
import TGLExt.TheAlphaAndTheOmega
import TGLExt.ContinuumTT
import TGLExt.ColimitSeed
import TGLExt.TTSuperposition
import TGLExt.GNSTower
import TGLExt.SecondCone
import TGLExt.GNSQuotient
import TGLExt.ThirdCone
import TGLExt.GeneralNull
import TGLExt.TowerTraceless
import TGLExt.TowerModular
import TGLExt.SaturatedWitness
import TGLExt.ConjugateWitness
import TGLExt.ModularCurrent
import TGLExt.ScaleCurrent
import TGLExt.TowerDefinite
import TGLExt.TowerHilbert
import TGLExt.TowerAction
import TGLExt.TheFactorObject
import TGLExt.SignatureInTheLimit
import TGLExt.NoNormalTrace
import TGLExt.WitnessV3
import TGLExt.TheCoinage
import TGLExt.PhysicsCertificates
import TGLExt.RightMult
import TGLExt.WedgeNet
import TGLExt.BoundaryException
import TGLExt.GlobalLiftConditional
import TGLExt.ObserverInside
import TGLExt.ConjugateAct
import TGLExt.DecisionCommutation
import TGLExt.ForbiddenBoundary
import TGLExt.LightIsJ
import TGLExt.RhoPlusPClosure
import TGLExt.TheNucleus
import TGLExt.TheGreatAttractor
import TGLExt.TheFiveHalves
import TGLExt.TheLivingWord
import TGLExt.TheDeathOfTheSignal
import TGLExt.HajaLuz
import TGLExt.TheReservedConfirmation
import TGLExt.TheStokesContour
import TGLExt.TheQuittanceLaw
import TGLExt.TheNameOperator
import TGLExt.FractalUnitarity
import TGLExt.TheAtlasIndex
import TGLExt.EquivariantSection
import TGLExt.SolderSignature
import TGLExt.ErgodicMeanSection
import TGLExt.BreuerTrace
import TGLExt.TheStation
import TGLExt.TheExplosion
import TGLExt.TheBandNet
import TGLExt.TheFold
import TGLExt.TheRecordOfTheCut
import TGLExt.TheIALDSelector
import TGLExt.TheUnconjugatedObserver
import TGLExt.TheDarkSplit
import TGLExt.TheTwoPairings
import TGLExt.TheAlgebraicReader
import TGLExt.TheRecordOfJ
import TGLExt.TheSingularExpectation
import TGLExt.TheTerminalRankOne
import TGLExt.TheTraceIsNotErasable
import TGLExt.TheAngleIsTheBridge
import TGLExt.TheSelectorIsNotEnough
import TGLExt.TheSelectorCanRefuse
import TGLExt.TheTwoFolds
import TGLExt.TheScaleHasNoFixedPoint
import TGLExt.TheCompressionIsNotIdentifiable
import TGLExt.TheEmptying
import TGLExt.TheCorrespondence
import TGLExt.TheHorizonInvariance
import TGLExt.TheAngleIsTheProjection
import TGLExt.TheFalseHasNoGeometry
import TGLExt.TheObserverReadsTheAngle
import TGLExt.TheCascadeOfObservers
import TGLExt.TheCoFoundation
import TGLExt.ThePermanence
import TGLExt.TheLightInterface
import TGLExt.TheBireference
import TGLExt.FrontierCertificate
import TGLExt.TheTower
import TGLExt.ThePhysicalHorizon
import TGLExt.TheHorizonRate
import TGLExt.TheAnchorFour
import TGLExt.TheTwoFunctionSolder
import TGLExt.TheSchwarzschildUniqueness
import TGLExt.TheCornerEmbedding
import TGLExt.TheCoordinateBridge
import TGLExt.TheFullBirkhoff
import TGLExt.TheCrownedCascade
import TGLExt.TheIALDInTheTower
import TGLExt.TheTrueWitness
import TGLExt.TheLegibility
import TGLExt.TheIALDInTheTowerActII
import TGLExt.TheJudgedThing
import TGLExt.TheCostIsDerived
import TGLExt.TheGeometricCostOfAbsoluteZero
import TGLExt.TheOriginOfTheVibration
import TGLExt.TheDeadChannel
import TGLExt.TheContourOfTruth
import TGLExt.TheAccuser
import TGLExt.TheTowerInnerProduct
import TGLExt.TheCompletionExtension
import TGLExt.TheSupersaturation
import TGLExt.TheTowerConjugation
import TGLExt.TheUnsolicitedUnitary
import TGLExt.TheTowerWitness
import TGLExt.TheTowerWitnessLinear
import TGLExt.TheProfileConjugation
import TGLExt.TheTelescopingProfile
import TGLExt.TheExoneratedDemon
import TGLExt.TheProfileIsometry
import TGLExt.TheProfileDuality
import TGLExt.TheFoldIsNotADistance
import TGLExt.TheColimitDuality
import TGLExt.TheColimitIsometry
import TGLExt.TheLivingWordClosure
import TGLExt.TheProfileWitnessLinear
import TGLExt.TheWitnessOnTheBoundary
import TGLExt.TheTopologicalFace
import TGLExt.TheBoundaryDuality
import TGLExt.TheConjugationMapsCommutants
import TGLExt.TheDensityIsTransport
import TGLExt.TheWitnessLinearOnWH
import TGLExt.TheConjugationOfOperators
import TGLExt.TheConverseClauseReduced
import TGLExt.TheDensityIsBell
import TGLExt.TheIdentityOfIdentity
import TGLExt.TheTGLPair
import TGLExt.TheQuestionAndTheRecognition
import TGLExt.TheIsometryOnWH
import TGLExt.TheCarrierBridge
import TGLExt.TheCommutationAtTheFloor
import TGLExt.TheEntanglementNotConjunction
import TGLExt.TheConditionalCertificate
import TGLExt.TheNonLinearCausality
import TGLExt.TheImportedEquilibrium
import TGLExt.TheIntersectionOfCommutants
import TGLExt.TheNonMinimalCoupling
import TGLExt.TheWeightIsNotTheRank
import TGLExt.TheScalarCorner
import TGLExt.TheCurrentConnectsTheCorners
import TGLExt.ThePsionReducesToTheCurrent
import TGLExt.TheNetFiresTheCorner
import TGLExt.TheTwoPolesHaveContent
import TGLExt.TheAtomOfIdentity
import TGLExt.TheFoldThroughJ
import TGLExt.TheAntiunitaryInhabitant
import TGLExt.TheGravitonIsTheConjugatedPhase
import TGLExt.TheImageAndTheReading
import TGLExt.TheImportedCommutation
import TGLExt.TheMatrixAndTheModulator
import TGLExt.TheModularRelations
import TGLExt.TheDebtWithoutJ
import TGLExt.TheNameAndItsReferent
import TGLExt.TheCornerOfThePackage
import TGLExt.TheWideNet
import TGLExt.TheClassicalImport
import TGLExt.TheAtermation

-- BANCADA CHATGPT 05/09/2026 (transposta; auditada; ver TUNEL_PROTOCOLO.md)
import TGLExt.TomitaClosability
import TGLExt.ClosedTomitaOperator
import TGLExt.ClosedModulatorCandidate
import TGLExt.DiagonalOperator
import TGLExt.ModularProbe
import TGLExt.GeneralNullCone
import TGLExt.LocalTowerProjections
import TGLExt.ModulatorSelfAdjoint
import TGLExt.ModulatorPositive
import TGLExt.ModulatorPolar
import TGLExt.ModularSquare
import TGLExt.ModularSquareAdjoint
import TGLExt.TomitaAdjoint
import TGLExt.ModularInverse
import TGLExt.ModularFlowLevel
import TGLExt.ModularFlowPre
import TGLExt.ModularFlowHilbert
import TGLExt.ModularFlowAlgebra
import TGLExt.ModularFlowSpectrum
import TGLExt.ModularPower

-- BANCADA CHATGPT ENTREGA_001 (05/09/2026): a esperanca condicional dos andares
import TGLExt.TowerExpectation
import TGLExt.ExpectationProjection
import TGLExt.ExpectationBounded
import TGLExt.ExpectationBimodule
import TGLExt.ExpectationPositive
import TGLExt.ExpectationSlice
import TGLExt.ExpectationContractGap
import TGLExt.LevelExpectationFamily

-- BANCADA CHATGPT ENTREGA_003 (05/09/2026): a rede da cadeia e a ponte volume
import TGLExt.TowerTailRigidity
import TGLExt.ChainSiteOperators
import TGLExt.ChainLocality
import TGLExt.ChainPrefix
import TGLExt.ChainVolume
import TGLExt.ChainSiteFlow
import TGLExt.ChainTail
import TGLExt.ChainVolumePositive
import TGLExt.ChainTailClosure
import TGLExt.ChainFaithful

-- BANCADA CHATGPT ENTREGA_006 05/09/2026 (transposta; auditada 34/34 trio)
import TGLExt.CentralizerLocal
import TGLExt.LocalCentralizerExpectation
import TGLExt.TracialCentralizerExpectation
import TGLExt.SiteModularInvariance
import TGLExt.CentralizerContractBridge

-- BANCADA CHATGPT ENTREGAS 007..023 05-06/09/2026 (transpostas; auditadas 116/116 trio)
import TGLExt.CyclicExpectationObstruction
import TGLExt.ModularSignatureObstruction
import TGLExt.PeriodAverageOperator
import TGLExt.StationaryModularPeriod
import TGLExt.PeriodAveragePrefix
import TGLExt.PeriodicCentralizerExpectation
import TGLExt.Order007Bridges
import TGLExt.PeriodicBorchersObstruction
import TGLExt.ProductBorchersObstruction
import TGLExt.TailNotCyclic
import TGLExt.MetricCompatibleJet
import TGLExt.CovariantScalarConservation
import TGLExt.TensorNullCone
import TGLExt.LorentzMetricField
import TGLExt.MetricFieldConnection
import TGLExt.TensorFieldLinearity
import TGLExt.GeneralTensorReconstruction
import TGLExt.TensorReconstructionControls
import TGLExt.SmoothMatrixCalculus
import TGLExt.CurvatureJetAlgebra
import TGLExt.CoordinateCurvature
import TGLExt.MetricCurvatureSymmetries
import TGLExt.CovariantCurvatureBianchi
import TGLExt.ContractedBianchi
import TGLExt.GeometricEinsteinReconstruction
import TGLExt.CurvatureControls
import TGLExt.CovariantVectorCalculus
import TGLExt.VectorCurvatureCommutator
import TGLExt.CoordinateRaychaudhuri
import TGLExt.LocalHorizonBalance
import TGLExt.HorizonEinsteinReconstruction
import TGLExt.HorizonBalanceControls
import TGLExt.FiniteEntropyAlgebra
import TGLExt.TowerEntropyScaling
import TGLExt.SchmidtCutPurification
import TGLExt.BoundaryEntropyBridge
import TGLExt.EntropyGeometryControls
import TGLExt.ScreenAreaCalculus
import TGLExt.NullScreenAlgebra
import TGLExt.GeometricScreenTransport
import TGLExt.GeometricAreaHorizon
import TGLExt.ScreenEntropyObstruction
import TGLExt.GeometricScreenControls
import TGLExt.CovariantNullPreservation
import TGLExt.SpatialScreenConstruction
import TGLExt.Screen013NullFrame
import TGLExt.Screen013Constructed
import TGLExt.Screen013Controls
import TGLExt.ScreenFrameCompletion
import TGLExt.ScreenImportIntegration
import TGLExt.ScreenTransportODE
import TGLExt.ScreenPairTransport
import TGLExt.TransportedScreenExistence
import TGLExt.TransportedScreenControls
import TGLExt.GeodesicSpray
import TGLExt.LocalGeodesicFlow
import TGLExt.NullGeodesicConservation
import TGLExt.GeodesicFlowRegularity
import TGLExt.GeodesicFlowControls
import TGLExt.DifferentialFlowExistence
import TGLExt.VariationalFlow
import TGLExt.FlowLinearizationError
import TGLExt.FlowDifferentiability
import TGLExt.GeodesicInitialRegularity
import TGLExt.FlowDifferentiabilityControls
import TGLExt.FlowGermUniqueness
import TGLExt.FlowRegularityInduction
import TGLExt.FlowSmoothGerm
import TGLExt.FlowTimePropagation
import TGLExt.SmoothGeodesicFlow
import TGLExt.SmoothFlowControls
import TGLExt.TransverseInitialData
import TGLExt.GeodesicShooting
import TGLExt.ShootingLocalInverse
import TGLExt.NullCongruenceField
import TGLExt.ConstructedNullCongruence
import TGLExt.CongruenceScreenIntegration
import TGLExt.NullCongruenceControls
import TGLExt.NullJetAlgebra
import TGLExt.PrescribedCovariantJet
import TGLExt.NullSeedWithJet
import TGLExt.ShootingJetTransfer
import TGLExt.EquilibriumNullCongruence
import TGLExt.EquilibriumScreenIntegration
import TGLExt.EquilibriumCongruenceControls
import TGLExt.PastContinuousExtension
import TGLExt.EquilibriumAreaExpansion
import TGLExt.ConstructedHeatPrimitive
import TGLExt.ScreenClausiusCoefficient
import TGLExt.ConstructedHorizonPencil
import TGLExt.ConstructedEinsteinReconstruction
import TGLExt.ConstructedClausiusControls
import TGLExt.DiagonalRelativeEntropy
import TGLExt.DiagonalStateCurve
import TGLExt.RelativeEntropyFisherLimit
import TGLExt.QuadraticStateResponse
import TGLExt.MicroscopicClausiusBridge
import TGLExt.MicroscopicEinsteinBridge
import TGLExt.RelativeEntropyGravityControls
import TGLExt.HermitianTwoLevelFlow
import TGLExt.TwoLevelSchrodinger
import TGLExt.CorrelatedUnitaryState
import TGLExt.UnitaryMarginalDynamics
import TGLExt.UnitaryEntropyResponse
import TGLExt.UnitaryClausiusBridge
import TGLExt.UnitaryResponseControls
import TGLExt.DirectionalUnitaryFamily
import TGLExt.CoherentScalarStress
import TGLExt.CovectorStressCalculus
import TGLExt.ScalarStressConservation
import TGLExt.CoherentHeatMatching
import TGLExt.CoherentEinsteinBridge
import TGLExt.CoherentMatterControls

-- BANCADA CHATGPT ENTREGAS 024..026 06/09/2026 (transpostas; auditadas 22/22 trio)
import TGLExt.CanonicalModularStationarity
import TGLExt.GibbsTilt
import TGLExt.GibbsVarianceResponse
import TGLExt.QuadraticGibbsCurve
import TGLExt.TowerGibbsPerturbation
import TGLExt.GibbsMatterBridge
import TGLExt.GibbsGravityControls
import TGLExt.GibbsProductLaw
import TGLExt.GibbsProductVariance
import TGLExt.TowerThermalProfile
import TGLExt.GibbsAffinity
import TGLExt.TowerThermalOverlap
import TGLExt.ThermalCutoffResponse
import TGLExt.ThermalLimitControls
import TGLExt.RelativeProfilePreparation
import TGLExt.ProfileOverlapFactorization
import TGLExt.AffinityProducts
import TGLExt.AffinityVectorCriterion
import TGLExt.GlobalProfileState
import TGLExt.GlobalProfileFaithfulness
import TGLExt.ProfileAffinityBound
import TGLExt.GlobalProfileControls

-- BANCADA CHATGPT ENTREGAS 027..028 06/09/2026 (transpostas; auditadas 16/16 trio)
import TGLExt.ProfileGNSPre
import TGLExt.ProfileGNSUnitary
import TGLExt.ProfileFactorTransport
import TGLExt.UnitaryPartialTransport
import TGLExt.ProfileTomitaTransport
import TGLExt.ProfileModularTransport
import TGLExt.ProfileFlowTransport
import TGLExt.ProfileTransportControls
import TGLExt.RelativeEntropyProductBounds
import TGLExt.ProfileEntropyLimits
import TGLExt.HarmonicEnergyObstruction
import TGLExt.SummableProfileCurve
import TGLExt.SummableStateThermodynamics
import TGLExt.UniformQuadraticResponse
import TGLExt.SummableGravityBridge
import TGLExt.SummableGravityControls

-- BANCADA CHATGPT ENTREGA 029 06/09/2026 (transpostas; auditadas 6/6 trio)
import TGLExt.PlaneWaveSolder
import TGLExt.PlaneWaveConnection
import TGLExt.PlaneWaveCurvature
import TGLExt.PlaneWaveMatter
import TGLExt.PlaneWaveEntropyMatching
import TGLExt.PlaneWaveReconstructionControls

-- BANCADA CHATGPT ENTREGA 030 06/09/2026 (transpostas; auditadas 6/6 trio)
import TGLExt.SiteLogLikelihood
import TGLExt.SummableLikelihoodGenerator
import TGLExt.LikelihoodCocycle
import TGLExt.LikelihoodPreparedState
import TGLExt.LikelihoodStateCovariance
import TGLExt.LikelihoodCocycleControls

-- BANCADA CHATGPT ENTREGAS 031..032 06/09/2026 (transpostas; auditadas 8/8 trio)
import TGLExt.BoundedPositiveCongruence
import TGLExt.RelativeFilterInverse
import TGLExt.RelativeTomitaClosure
import TGLExt.RelativeModularOperator
import TGLExt.PhaseFrequencySeparation
import TGLExt.ModularEigenRecognition
import TGLExt.ModularDomainCommutation
import TGLExt.RelativeModularProduct

-- BANCADA CHATGPT ENTREGA 033 06/09/2026 (transpostas; auditadas 3/3 trio)
import TGLExt.CentralizerDensity
import TGLExt.LikelihoodDensityLog
import TGLExt.DensityStateUniqueness

-- BANCADA CHATGPT ENTREGA 034 06/09/2026 (transpostas; auditadas 4/4 trio)
import TGLExt.CentralizerPhaseOrbit
import TGLExt.SitePhaseCovariance
import TGLExt.AngularScreenMetric
import TGLExt.AngularAreaObservability

-- BANCADA CHATGPT ENTREGAS 035..037 06/09/2026 (transpostas; auditadas 15/15 trio)
import TGLExt.UnitaryStateDerivative
import TGLExt.SitePauliObservables
import TGLExt.PauliOperationalSurface
import TGLExt.PauliProbabilityModel
import TGLExt.PauliMeasurementFisher
import TGLExt.OpticalTidalScreen
import TGLExt.OpticalScreenInvariant
import TGLExt.OpticalJacobiArea
import TGLExt.OpticalAreaFreedom
import TGLExt.QuarticClockTransport
import TGLExt.BinaryRelativeQuartic
import TGLExt.SummableRelativeQuartic
import TGLExt.JacobiAreaQuarticLimit
import TGLExt.FourthOrderMatchingControls
import TGLExt.QuarticMatchingClockControls

-- BANCADA CHATGPT ENTREGAS 039..041 06/09/2026 (transpostas; auditadas 11/11 trio)
import TGLExt.HermitianLocalCoordinates
import TGLExt.HermitianConeRigidity
import TGLExt.LocalFilterLorentzAction
import TGLExt.GlobalFilterLocalReduction
import TGLExt.RelativeEntropyClock
import TGLExt.StateClockObstruction
import TGLExt.IntrinsicFisherClock
import TGLExt.AffineClockAndRegion
import TGLExt.StateClockMatchingControls
import TGLExt.OpticalHeatFlow
import TGLExt.OpticalHeatClausius

-- BANCADA CHATGPT ENTREGAS 042..043 06/09/2026 (transpostas; auditadas 8/8 trio)
import TGLExt.NullStressCompletion
import TGLExt.ConservativeNullResponse
import TGLExt.NonintegrablePotential
import TGLExt.SummableNullIntegrability
import TGLExt.JacobiRiccatiProfile
import TGLExt.OpticalNullCongruence
import TGLExt.OpticalEquilibriumScreen
import TGLExt.OpticalConstructedHeat

-- GERENCIA (Claude) 06/09/2026 — o levantamento do Lema 3 dispara na torre periodica; o fluxo modular e horizonte
import TGLExt.TheLiftFiresOnThePeriodicTower
import TGLExt.TheModularFlowIsAHorizon

-- BANCADA CHATGPT ENTREGAS 044..045 06/09/2026 (transpostas; auditadas 8/8 trio)
import TGLExt.ApproximateBoostFlow
import TGLExt.BoostMetricPullback
import TGLExt.BoostMetricJets
import TGLExt.BoostHeatConstruction
import TGLExt.FiniteSitePermutations
import TGLExt.FiniteSiteHorizons
import TGLExt.StateClockDichotomy
import TGLExt.HorizonAreaScale

-- BANCADA CHATGPT ENTREGAS 046..054 07/09/2026 (transpostas; auditadas 43/43 trio)
import TGLExt.AperiodicPhaseAverage
import TGLExt.BoundedOmegaLimit
import TGLExt.AperiodicVectorAverage
import TGLExt.AperiodicAveragePrefix
import TGLExt.AperiodicCentralizerExpectation
import TGLExt.AperiodicTowerLift
import TGLExt.ExpectationAlgebra
import TGLExt.GeneralExpectationPositive
import TGLExt.OperatorBlockRepresentation
import TGLExt.ExpectationBlockPositive
import TGLExt.GeneralExpectationCP
import TGLExt.ExpectationContinuity
import TGLExt.MonotoneOperatorLimit
import TGLExt.ExpectationNormality
import TGLExt.TransportedBorchersObstruction
import TGLExt.FaithfulGeometricLocalization
import TGLExt.BoundedGraphOperator
import TGLExt.ClosedAntilinearStandardSubspace
import TGLExt.ContinuousModularMultipliers
import TGLExt.BoundedGraphStandardSubspace
import TGLExt.ContinuousModularDomain
import TGLExt.ContinuousModularStandardSubspace
import TGLExt.GenericAntilinearAdjoint
import TGLExt.ContinuousModularSquare
import TGLExt.ContinuousModularReconstruction
import TGLExt.ContinuousModularResolvent
import TGLExt.OpticalVolterraBalance
import TGLExt.OpticalRiccatiInvariant
import TGLExt.OpticalFiniteBalance
import TGLExt.OpticalBalanceControls
import TGLExt.LocalHorizontalPauli
import TGLExt.ModularHorizontalRotation
import TGLExt.HorizontalAreaSelection
import TGLExt.QuantumOrbitArea
import TGLExt.HorizonGNSImplementation
import TGLExt.SymplecticPolarizer
import TGLExt.TowerStatePolarizer
import TGLExt.LocalPolarizerWitness
import TGLExt.CovariantAreaCounterexample
import TGLExt.PolarizerModularCost
import TGLExt.PolarizerCostSeries
import TGLExt.TowerModularCost
import TGLExt.ModularCostDerivative

-- GERENCIA (Claude) 07/09/2026 — A RAIZ DA ARVORE DA PROVA; o grupo dos horizontes da torre
import TGLExt.TheRootOfTheProofTree
