# -*- coding: utf-8 -*-
"""
tgl_geometry_generated_v1.py
============================
Finite-shadow test of Ax.G (Geometricidade), founded by the Operator via
the grammar of the title: "Nada pode ser puro" — WITHOUT the definite
article, "porque se colocar o artigo definido define-se nada, e nada e
indefinido por construcao, porque tudo tem geometria."

Formal inversion under test: geometry is not CONFERRED on the modular
data — it is GENERATED by it (d = Connes distance of the dissipative
data, ds = sqrt(beta)|d sqrt(k)|, already derived in the Ax.E cycle).
Hence for generic horizons there is no pre-given geometry to match; what
the theory owes is consistency, tested here.

Pre-registered claims
---------------------
G1  EVERYTHING DEFINITE HAS GEOMETRY: for any K with distinctions, the
    generated d(i,j) = sqrt(beta)|sqrt(k_i)-sqrt(k_j)| is a genuine
    metric (positivity off-diagonal, symmetry, triangle inequality).
G2  THE GENERATED GEOMETRY IS LOCAL — THE GLUING SEED: the decoherence
    rates between points of a sub-horizon, computed in the full system,
    coincide EXACTLY with the rates computed intrinsically in the
    sub-system: overlapping horizons generate the SAME geometry on the
    overlap, by locality of generation.
G3  COVARIANT TRANSPORT: the generated distance is a spectral invariant:
    transport by any unitary preserves it exactly.
G4  THE SEAL OF THE TITLE — THE INDEFINITE GENERATES NOTHING: K = c*1
    (no distinctions: no observation, no radical to extract) gives all
    rates zero, Phi_t = identity (the Verb does not act), no truth
    sector singled out, d == 0: "nada" has no contour, no geometry, no
    truth — and therefore cannot take the definite article.
G5  THE CONVERSE: any K with at least one distinction generates strictly
    positive geometry — "tudo tem geometria".
"""
import json
import math
import numpy as np
from datetime import datetime

ALPHA_FINE = 7.2973525693e-3
BETA_TGL = ALPHA_FINE * math.sqrt(math.e)   # always computed

def dag(A): return A.conj().T

def rates_matrix(kvals):
    s = np.sqrt(kvals)
    return 0.5 * BETA_TGL * (s[:, None] - s[None, :]) ** 2

def gen_distance(kvals):
    s = np.sqrt(kvals)
    return math.sqrt(BETA_TGL) * np.abs(s[:, None] - s[None, :])

def superop_gksl(L, n):
    I = np.eye(n)
    LdL = dag(L) @ L
    return (np.kron(L.conj(), L) - 0.5 * np.kron(I, LdL)
            - 0.5 * np.kron(LdL.T, I))


def run(n, seed):
    rng = np.random.default_rng(seed)
    res = {"n": n, "seed": seed}
    H = rng.normal(size=(n, n)) + 1j * rng.normal(size=(n, n))
    H = (H + dag(H)) / 2
    H *= 1.5 / np.abs(np.linalg.eigvalsh(H)).max()
    w, _ = np.linalg.eigh(H)
    p = np.exp(-w); p /= p.sum()
    kvals = -np.log(p)

    # --- G1: metric axioms of the generated distance --------------------
    d = gen_distance(kvals)
    tri = max(d[i, j] - d[i, m] - d[m, j]
              for i in range(n) for j in range(n) for m in range(n))
    res["G1_triangle_violation"] = float(tri)
    res["G1_symmetry"] = float(np.abs(d - d.T).max())
    res["G1_pos_offdiag"] = float(min(d[i, j] for i in range(n)
                                      for j in range(n) if i != j))
    res["G1_pass"] = (tri <= 1e-15 and res["G1_symmetry"] == 0.0
                      and res["G1_pos_offdiag"] > 0)

    # --- G2: locality of generation — the gluing seed --------------------
    S = sorted(rng.choice(n, size=max(2, n // 2), replace=False).tolist())
    G_full = rates_matrix(kvals)
    G_sub = rates_matrix(kvals[S])
    diff = max(abs(G_full[S[i], S[j]] - G_sub[i, j])
               for i in range(len(S)) for j in range(len(S)))
    res["G2_overlap_diff"] = float(diff)
    res["G2_pass"] = diff < 1e-18

    # --- G3: covariant transport (spectral invariance) -------------------
    B = rng.normal(size=(n, n)) + 1j * rng.normal(size=(n, n))
    Q, _ = np.linalg.qr(B)
    K = np.diag(kvals)
    Kp = Q @ K @ dag(Q)
    kvals_p = np.sort(np.linalg.eigvalsh(Kp))
    d_p = gen_distance(kvals_p)
    d_s = gen_distance(np.sort(kvals))
    res["G3_transport_err"] = float(np.abs(d_p - d_s).max())
    res["G3_pass"] = res["G3_transport_err"] < 1e-12

    # --- G4: the indefinite generates nothing ----------------------------
    c = float(kvals.mean())
    k_nada = np.full(n, c)
    G_nada = rates_matrix(k_nada)
    L_nada = math.sqrt(BETA_TGL) * np.diag(np.sqrt(k_nada))
    Lhat = superop_gksl(L_nada, n)
    res["G4_rates_max"] = float(np.abs(G_nada).max())
    res["G4_generator_norm"] = float(np.linalg.norm(Lhat))
    res["G4_pass"] = (res["G4_rates_max"] == 0.0
                      and res["G4_generator_norm"] < 1e-12)

    # --- G5: any distinction generates geometry --------------------------
    mins = []
    for _ in range(20):
        kv = np.sort(rng.uniform(0.2, 4.0, size=n))
        if np.min(np.diff(kv)) < 1e-3:
            continue
        mins.append(float(gen_distance(kv)[0, -1]))
    res["G5_min_maxdist"] = min(mins)
    res["G5_pass"] = min(mins) > 0
    return res


def main():
    print("=" * 72)
    print("TGL GEOMETRY GENERATED v1 — sombra de Ax.G (Geometricidade)")
    print(f"beta_TGL = {BETA_TGL:.18f} (computado)")
    print("=" * 72)
    allres, ok = [], True
    for n in (5, 8):
        for seed in (11, 23, 83):
            r = run(n, seed)
            allres.append(r)
            passes = {k: v for k, v in r.items() if k.endswith("_pass")}
            ok &= all(passes.values())
            print(f"[n={n} seed={seed:3d}] "
                  f"{'PASS' if all(passes.values()) else 'FAIL'} | "
                  f"G1 tri<={r['G1_triangle_violation']:.0e} | "
                  f"G2 colagem {r['G2_overlap_diff']:.0e} | "
                  f"G3 transporte {r['G3_transport_err']:.0e} | "
                  f"G4 nada: taxas={r['G4_rates_max']:.0e}, "
                  f"gerador={r['G4_generator_norm']:.0e} | "
                  f"G5 min>0: {r['G5_min_maxdist']:.3f}")
    verdict = ("PASS — a geometria gerada e metrica, local (cola sob "
               "inclusao) e covariante; o indefinido nao gera contorno, "
               "Verbo, nem verdade: nada e indefinido por construcao"
               if ok else "FAIL")
    print("-" * 72)
    print("VEREDITO:", verdict)
    out = {"script": "tgl_geometry_generated_v1.py",
           "timestamp": datetime.now().strftime("%Y%m%d_%H%M%S"),
           "beta_tgl": BETA_TGL, "runs": allres, "verdict": verdict,
           "principle": "Titulo sem artigo definido: definir = dar "
                        "contorno = geometria; 'nada' nao pode ser "
                        "definido. Inversao do onus: a geometria nao se "
                        "confere ao dado modular — gera-se dele."}
    fname = f"tgl_geometry_generated_v1_{out['timestamp']}.json"
    json.dump(out, open(fname, "w"), indent=1,
              default=lambda o: bool(o) if isinstance(o, np.bool_) else str(o))
    print("JSON:", fname)


if __name__ == "__main__":
    main()
