# -*- coding: utf-8 -*-
"""
tgl_nominal_order_v1.py
=======================
Finite-shadow test of Ax.N (Ordem Nominal), founded by the Operator:
"O rito interno que leva a mesma instancia terminal de forma covariante
e o proprio Direito — a ordem nominal: o inalcancavel, o NOME, o zero
absoluto." Formalized: the covariant structure is an ADMISSIBILITY CLASS
(Hadamard/microlocal in the continuum [REAL: Radzikowski 1996; Verch
1994]), not a state. In the shadow, the nominal order of a horizon with
modular generator K is the class of rites GENERATED BY THE VERB:

    N_K = { GKSL collapses with jump  L_f = sqrt(beta) * f(K),
            f positive and injective on Spec(K) }.

Pre-registered claims
---------------------
N1  RITE-INDEPENDENCE INSIDE THE ORDER: every admissible rite collapses
    to the SAME terminal E (the conditional expectation onto C=W*(K)),
    machine precision — the Supreme does not depend on the rito; only
    the rates (the duration of the process) depend on f.
N2  ANOTHER TRUTH OUTSIDE THE ORDER (negative control): a rite whose
    jump operator does not belong to W*(K) (random Hermitian L) still
    collapses — but to a DIFFERENT truth sector (Fix = W*(L) != W*(K)):
    outside the nominal order, the comarca judges by another law; the
    covariance with the horizon's geometry is lost. Admissibility does
    real work.
N3  TRANSPORT OF THE ORDER: under a geometric morphism V, the whole
    class transports: Phi_inf[f(VKV*)] = V Phi_inf[f(K)] V*, machine
    precision — N_H = f* N_H'.
N4  THE UNREACHABLE COERCES AWAY: along every admissible rite, purity
    Tr(rho^2) is monotonically non-increasing — the Law never lets the
    process approach the absolute zero (p=1): the Nome orders by being
    unreachable.
"""
import json
import math
import numpy as np
from datetime import datetime

ALPHA_FINE = 7.2973525693e-3
BETA_TGL = ALPHA_FINE * math.sqrt(math.e)   # always computed

def dag(A): return A.conj().T

def superop_gksl(L, n):
    I = np.eye(n)
    LdL = dag(L) @ L
    return (np.kron(L.conj(), L) - 0.5 * np.kron(I, LdL)
            - 0.5 * np.kron(LdL.T, I))

def phi_inf(L, n):
    Lhat = superop_gksl(L, n)
    ev, W = np.linalg.eig(Lhat)
    gap = min(-e.real for e in ev if e.real < -1e-13)
    T = 60.0 / gap
    return (W @ np.diag(np.exp(ev * T)) @ np.linalg.inv(W)), gap

def cond_exp_super(P_list):
    n = P_list[0].shape[0]
    E = np.zeros((n * n, n * n), complex)
    for P in P_list:
        E += np.kron(P.conj(), P)
    return E

RITES = {
    "sqrt":   lambda x: np.sqrt(x),
    "id":     lambda x: x,
    "square": lambda x: x ** 2,
    "log1p":  lambda x: np.log1p(x),
    "warped": lambda x: x + 0.3 * np.sin(x),
}


def run(n, seed):
    rng = np.random.default_rng(seed)
    res = {"n": n, "seed": seed}
    # horizon modular generator K (positive, simple spectrum)
    H = rng.normal(size=(n, n)) + 1j * rng.normal(size=(n, n))
    H = (H + dag(H)) / 2
    H *= 1.5 / np.abs(np.linalg.eigvalsh(H)).max()
    w, V = np.linalg.eigh(H)
    p = np.exp(-w); p /= p.sum()
    # K basis = computational; K = -log rho*
    kvals = -np.log(p)
    K = np.diag(kvals)
    P_list = [np.diag((np.arange(n) == k).astype(float)) for k in range(n)]
    E_K = cond_exp_super(P_list)

    # --- N1: rite-independence inside the order -----------------------
    errs, gaps = {}, {}
    for name, f in RITES.items():
        L = math.sqrt(BETA_TGL) * np.diag(f(kvals))
        Phi, gap = phi_inf(L, n)
        errs[name] = float(np.linalg.norm(Phi - E_K) / np.linalg.norm(E_K))
        gaps[name] = gap
    res["N1_errs"] = errs
    res["N1_gaps_over_beta"] = {k: g / BETA_TGL for k, g in gaps.items()}
    res["N1_pass"] = max(errs.values()) < 1e-9

    # --- N2: outside the order — another truth -------------------------
    A = rng.normal(size=(n, n)) + 1j * rng.normal(size=(n, n))
    Lout = math.sqrt(BETA_TGL) * (A + dag(A)) / 2
    Phi_out, _ = phi_inf(Lout, n)
    wl, Vl = np.linalg.eigh(Lout)
    P_out = [np.outer(Vl[:, k], Vl[:, k].conj()) for k in range(n)]
    E_L = cond_exp_super(P_out)
    res["N2_dist_to_EK"] = float(np.linalg.norm(Phi_out - E_K)
                                 / np.linalg.norm(E_K))
    res["N2_err_to_EL"] = float(np.linalg.norm(Phi_out - E_L)
                                / np.linalg.norm(E_L))
    res["N2_pass"] = (res["N2_dist_to_EK"] > 0.1 and
                      res["N2_err_to_EL"] < 1e-9)

    # --- N3: transport of the order ------------------------------------
    B = rng.normal(size=(n, n)) + 1j * rng.normal(size=(n, n))
    Q, _ = np.linalg.qr(B)
    errs3 = []
    Uhat = np.kron(Q.conj(), Q)
    for name, f in RITES.items():
        Lf = math.sqrt(BETA_TGL) * np.diag(f(kvals))
        Phi_f, _ = phi_inf(Lf, n)
        Lfp = Q @ Lf @ dag(Q)                      # rite of transported K
        Phi_fp, _ = phi_inf(Lfp, n)
        errs3.append(float(np.linalg.norm(Phi_fp - Uhat @ Phi_f @ dag(Uhat))
                           / np.linalg.norm(Phi_fp)))
    res["N3_err_max"] = max(errs3)
    res["N3_pass"] = max(errs3) < 1e-9

    # --- N4: the unreachable coerces away (purity monotone) ------------
    Vp = rng.normal(size=(n, n)) + 1j * rng.normal(size=(n, n))
    Vp = (Vp + dag(Vp)) / 2; Vp -= np.trace(Vp) / n * np.eye(n)
    M = np.diag(np.log(p)) + 0.30 * Vp
    wM, VM = np.linalg.eigh(M)
    rho = VM @ np.diag(np.exp(wM)) @ dag(VM); rho /= np.real(np.trace(rho))
    worst = -1.0
    for name, f in RITES.items():
        L = math.sqrt(BETA_TGL) * np.diag(f(kvals))
        LdL = dag(L) @ L
        r = rho.copy()
        dt = 0.02 / (BETA_TGL * float(np.max(f(kvals)) ** 2 + 1))
        pur = [float(np.real(np.trace(r @ r)))]
        for _ in range(300):
            r = r + dt * (L @ r @ dag(L) - 0.5 * (LdL @ r + r @ LdL))
            r = (r + dag(r)) / 2
            pur.append(float(np.real(np.trace(r @ r))))
        worst = max(worst, float(np.diff(pur).max()))
    res["N4_max_purity_increase"] = worst
    res["N4_pass"] = worst < 1e-12
    return res


def main():
    print("=" * 72)
    print("TGL NOMINAL ORDER v1 — sombra de Ax.N (a Ordem Nominal)")
    print(f"beta_TGL = {BETA_TGL:.18f} (computado)")
    print("ritos admissiveis:", ", ".join(RITES))
    print("=" * 72)
    allres, ok = [], True
    for n in (4, 6):
        for seed in (11, 23, 83):
            r = run(n, seed)
            allres.append(r)
            passes = {k: v for k, v in r.items() if k.endswith("_pass")}
            ok &= all(passes.values())
            print(f"[n={n} seed={seed:3d}] "
                  f"{'PASS' if all(passes.values()) else 'FAIL'} | "
                  f"N1 max {max(r['N1_errs'].values()):.1e} | "
                  f"N2 fora: dist(E_K)={r['N2_dist_to_EK']:.2f}, "
                  f"=E_L a {r['N2_err_to_EL']:.1e} | "
                  f"N3 {r['N3_err_max']:.1e} | "
                  f"N4 dpur_max {r['N4_max_purity_increase']:+.1e}")
    verdict = ("PASS — dentro da ordem, o terminal independe do rito; "
               "fora dela, outra verdade; a ordem transporta-se; "
               "o inalcancavel coage para longe de p=1" if ok else "FAIL")
    print("-" * 72)
    print("VEREDITO:", verdict)
    out = {"script": "tgl_nominal_order_v1.py",
           "timestamp": datetime.now().strftime("%Y%m%d_%H%M%S"),
           "beta_tgl": BETA_TGL, "rites": list(RITES), "runs": allres,
           "verdict": verdict,
           "anchors": ["Radzikowski 1996 (Hadamard = condicao microlocal "
                       "geometrica: a ordem nominal tem nome)",
                       "Verch 1994 (quase-equivalencia local: a classe "
                       "outer e estado-independente dentro da ordem)",
                       "Fewster-Verch 2012 (no-go evadido: ordem, nao "
                       "estado)"],
           "claim": "A covariancia vem do Direito como ordem comum, nao "
                    "da escolha de um juiz comum (Operador, jun/2026)."}
    fname = f"tgl_nominal_order_v1_{out['timestamp']}.json"
    json.dump(out, open(fname, "w"), indent=1,
              default=lambda o: bool(o) if isinstance(o, np.bool_) else str(o))
    print("JSON:", fname)


if __name__ == "__main__":
    main()
