import TGLExt.V350FibreSlices
import TGLExt.V350DualOrbitVonNeumann
import TGLExt.V350ReducingCommutantTransport
import TGLExt.V350ScalarGNSRepresentation

set_option autoImplicit false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1500000

namespace TGLV350.Regular
open TGLExt
noncomputable section
variable {H : Type} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

theorem dualOrbit_generated_mem
    (S : Set (RegularHilbert H →L[ℂ] RegularHilbert H))
    (A : RegularHilbert H →L[ℂ] RegularHilbert H) (hA : A ∈ generatedAlgebra S) :
    dualOrbitRepresentation A ∈ generatedAlgebra ((dualOrbitRepresentation (H := H)) '' S) := by
  have hi : dualOrbitConjugation (H := H) '' (fibre '' S) =
      (dualOrbitRepresentation (H := H)) '' S := by
    rw [Set.image_image]
    congr 1
    funext B
    exact dualOrbitConjugation_fibre B
  have ht := (generated_transport (dualOrbitConjugation (H := H))
    (fibre '' S) (fibre A)).mpr (fibre_generated_mem S A hA)
  simpa only [hi,dualOrbitConjugation_fibre] using ht

theorem regularGenerators_star (P : SiteProfile)
    (A : RegularHilbert (TowerHilbert P) →L[ℂ] RegularHilbert (TowerHilbert P))
    (hA : A ∈ regularGenerators P) : star A ∈ regularGenerators P := by
  rcases hA with ⟨B,hB,rfl⟩ | ⟨t,rfl⟩
  · rw [← fibre_star]
    exact Or.inl ⟨star B,star_mem hB,rfl⟩
  · rw [regular_star]
    exact Or.inr ⟨-t,rfl⟩

def scalarCoreGenerators (P : SiteProfile) : Set (regularCoreAlgebra P).toStarSubalgebra :=
  {A | A.val ∈ regularGenerators P}

/-- Bicommutant generation is transported through the concrete dual-orbit
amplification, before restricting to the GNS subspace. -/
theorem dualOrbit_core_commutation_from_generators (P : SiteProfile)
    (T : RegularHilbert (RegularHilbert (TowerHilbert P)) →L[ℂ]
      RegularHilbert (RegularHilbert (TowerHilbert P)))
    (hT : ∀ A ∈ scalarCoreGenerators P, Commute T (dualOrbitRepresentation A.val)) :
    ∀ A : (regularCoreAlgebra P).toStarSubalgebra,
      Commute T (dualOrbitRepresentation A.val) := by
  have hc : T ∈ StarSubalgebra.centralizer ℂ
      (dualOrbitRepresentation '' regularGenerators P) := by
    rw [StarSubalgebra.mem_centralizer_iff]
    rintro _ ⟨B,hB,rfl⟩
    constructor
    · exact (hT ⟨B,generator_mem hB⟩ hB).eq.symm
    · rw [← map_star]
      exact (hT ⟨star B,generator_mem (regularGenerators_star P B hB)⟩
        (regularGenerators_star P B hB)).eq.symm
  intro A
  have ha := dualOrbit_generated_mem (regularGenerators P) A.val A.property
  change dualOrbitRepresentation A.val ∈ StarSubalgebra.centralizer ℂ
    ((StarSubalgebra.centralizer ℂ (dualOrbitRepresentation '' regularGenerators P)) :
      Set (RegularHilbert (RegularHilbert (TowerHilbert P)) →L[ℂ]
        RegularHilbert (RegularHilbert (TowerHilbert P)))) at ha
  exact (((StarSubalgebra.mem_centralizer_iff ℂ).mp ha) T hc).1

/-- The actual scalar GNS representation is generated by the represented
regular generators. There is no residual normality or density hypothesis. -/
theorem scalarGNS_commutation_from_generators (P : SiteProfile)
    (T : ScalarGNSHilbert P →L[ℂ] ScalarGNSHilbert P)
    (hT : ∀ A ∈ scalarCoreGenerators P, Commute T (scalarGNSRepresentation P A)) :
    ∀ A : (regularCoreAlgebra P).toStarSubalgebra,
      Commute T (scalarGNSRepresentation P A) := by
  apply reducing_commutation_from_generators
    (dualOrbitRepresentation.comp (regularCoreAlgebra P).toStarSubalgebra.subtype)
    (scalarGNSSubspace P) (scalarGNSAmbientAction_preserves P) (scalarCoreGenerators P)
  · exact dualOrbit_core_commutation_from_generators P
  · exact hT

#print axioms dualOrbit_generated_mem
#print axioms regularGenerators_star
#print axioms scalarCoreGenerators
#print axioms dualOrbit_core_commutation_from_generators
#print axioms scalarGNS_commutation_from_generators
end
end TGLV350.Regular
