import TGLExt.V350RegularTowerRepresentation

set_option autoImplicit false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1000000

namespace TGLV350.Regular
open TGLExt ChatgptAudit
noncomputable section

variable {H : Type} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- The von Neumann algebra generated by a set, using the star-bicommutant definition. -/
def generatedAlgebra (S : Set (H →L[ℂ] H)) : VonNeumannAlgebra H where
  toStarSubalgebra := StarSubalgebra.centralizer ℂ
    ((StarSubalgebra.centralizer ℂ S) : Set (H →L[ℂ] H))
  centralizer_centralizer' := by simp

theorem generator_mem {S : Set (H →L[ℂ] H)} {A : H →L[ℂ] H} (hA : A ∈ S) :
    A ∈ generatedAlgebra S := by
  change A ∈ StarSubalgebra.centralizer ℂ
    ((StarSubalgebra.centralizer ℂ S) : Set (H →L[ℂ] H))
  rw [StarSubalgebra.mem_centralizer_iff]
  intro B hB
  rw [SetLike.mem_coe, StarSubalgebra.mem_centralizer_iff] at hB
  have h := hB A hA
  refine ⟨h.1.symm, ?_⟩
  have hs := congrArg star h.2
  rw [star_mul, star_mul, star_star] at hs
  exact hs

theorem generated_minimal (S : Set (H →L[ℂ] H)) (N : VonNeumannAlgebra H)
    (hN : S ⊆ (N : Set (H →L[ℂ] H))) : generatedAlgebra S ≤ N := by
  have hfirst := StarSubalgebra.centralizer_le ℂ S (N : Set (H →L[ℂ] H)) hN
  have hsecond := StarSubalgebra.centralizer_le ℂ
    ((StarSubalgebra.centralizer ℂ (N : Set (H →L[ℂ] H))) : Set (H →L[ℂ] H))
    ((StarSubalgebra.centralizer ℂ S) : Set (H →L[ℂ] H)) hfirst
  intro A hA
  have h := hsecond hA
  simpa only [← SetLike.mem_coe, StarSubalgebra.coe_centralizer_centralizer,
    StarMemClass.star_coe_eq, Set.union_self, VonNeumannAlgebra.centralizer_centralizer] using h

def regularGenerators (P : SiteProfile) :
    Set (RegularHilbert (TowerHilbert P) →L[ℂ] RegularHilbert (TowerHilbert P)) :=
  (fibre '' (theFactorObject P : Set (TowerHilbert P →L[ℂ] TowerHilbert P))) ∪
    Set.range (regularUnitary P)

/-- The algebra generated by the faithful amplified tower and its continuous regular unitaries.
No trace, semifiniteness, or Three-Locks corner is asserted by this definition. -/
def regularCoreAlgebra (P : SiteProfile) : VonNeumannAlgebra (RegularHilbert (TowerHilbert P)) :=
  generatedAlgebra (regularGenerators P)

theorem amplified_factor_mem (P : SiteProfile) (A : TowerHilbert P →L[ℂ] TowerHilbert P)
    (hA : A ∈ theFactorObject P) : fibre A ∈ regularCoreAlgebra P :=
  generator_mem (Or.inl ⟨A, hA, rfl⟩)

theorem regularUnitary_mem (P : SiteProfile) (t : ℝ) :
    regularUnitary P t ∈ regularCoreAlgebra P :=
  generator_mem (Or.inr ⟨t, rfl⟩)

def factorAmplification (P : SiteProfile) :
    (theFactorObject P).toStarSubalgebra →⋆ₐ[ℂ]
      (RegularHilbert (TowerHilbert P) →L[ℂ] RegularHilbert (TowerHilbert P)) :=
  fibreRepresentation.comp (theFactorObject P).toStarSubalgebra.subtype

def regularCoreEmbedding (P : SiteProfile) :
    (theFactorObject P).toStarSubalgebra →⋆ₐ[ℂ] (regularCoreAlgebra P).toStarSubalgebra :=
  (factorAmplification P).codRestrict (regularCoreAlgebra P).toStarSubalgebra
    (fun A => amplified_factor_mem P A A.property)

theorem regularCoreEmbedding_injective (P : SiteProfile) :
    Function.Injective (regularCoreEmbedding P) := by
  intro A B h
  apply Subtype.ext
  apply fibre_injective
  exact congrArg Subtype.val h

theorem regularCore_minimal (P : SiteProfile)
    (N : VonNeumannAlgebra (RegularHilbert (TowerHilbert P)))
    (hM : ∀ A ∈ theFactorObject P, fibre A ∈ N)
    (hU : ∀ t : ℝ, regularUnitary P t ∈ N) : regularCoreAlgebra P ≤ N := by
  apply generated_minimal
  intro A hA
  rcases hA with ⟨B, hB, rfl⟩ | ⟨t, rfl⟩
  · exact hM B hB
  · exact hU t

#print axioms regularCoreAlgebra
#print axioms regularCoreEmbedding_injective
#print axioms regularCore_minimal
end
end TGLV350.Regular
