# -*- coding: utf-8 -*-
"""ESTADO_ATUAL.md — one page, generated from the seal. Never edited by hand.

The README is the ledger (2,000+ lines, 134 seals). A reader from outside, or an AI,
needs one page first: the pin, the gate, what is PROVED, what is NOT, how to reproduce.
Every number below is read from the sealed artifacts at generation time; the
qualitative lines are updated at each custody, beside the numbers, never over them.

Uso:  python tools/gerar_estado_atual.py     (before tools/gerar_portas.py in the chain)
"""
import hashlib
import json
import re
import sys
import urllib.parse
from pathlib import Path

RAIZ = Path(__file__).resolve().parent.parent
A3 = "Um (absoluto) — Grande Atrator"
RAW = "https://raw.githubusercontent.com/rotolimiguel-iald/the_boundary/main/"
TRIO = ("propext", "Classical.choice", "Quot.sound")


def raw(rel: str) -> str:
    return RAW + urllib.parse.quote(rel)


def sha16(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()[:16]


def main() -> int:
    d = RAIZ / A3
    selo = json.loads((d / "um_absoluto_selo.json").read_text(encoding="utf-8"))
    man = json.loads((d / "Lean" / "tgl_kernel_proof_manifest.json").read_text(encoding="utf-8"))
    ar, fmap = man["axiom_report"], man["formal_files_sha256"]
    sujos = sum(1 for v in ar.values() if any(a not in TRIO for a in (v or [])))
    livres = sum(1 for v in ar.values() if not v)
    b = (d / "um.py").read_bytes()
    linhas, nbytes = b.count(b"\n"), len(b)
    pin, mundo, ts = selo["sha256"]["um.py"], selo["result_hash"], selo["timestamp"]
    gate = selo.get("qg_closure_verdict", "?")
    rc = selo.get("rite_checkpoints") or {}
    rodadas = sorted(d.glob("rodadas/rodada_v*_stdout.txt"), key=lambda p: int(re.search(r"v(\d+)", p.name).group(1)))
    ultima = rodadas[-1] if rodadas else None
    versao = re.search(r"v(\d+)", ultima.name).group(1) if ultima else "?"
    std = ultima.read_text(encoding="utf-8", errors="replace") if ultima else ""
    m = re.search(r"(\d+)/(\d+) teoremas", std) or re.search(r"\b(\d{3,4})/(\d{3,4})\b", std)
    rito = m.group(0) if m else "?"
    assert rito != "?", "contagem do rito nao localizada no stdout — PARAR (o numero corrige a frase)"
    raiz_ax = ar.get("TGLExt.the_root_of_the_proof_tree")
    raiz_f = d / "Lean" / "tgl_kernel" / "TGLExt" / "TheRootOfTheProofTree.lean"
    raiz_sha = sha16(raiz_f) if raiz_f.is_file() else None
    assert sujos == 0, "axiom_report fora do trio: %d — PARAR" % sujos

    L = []
    L.append("# The Boundary — current state · estado atual")
    L.append("")
    L.append("> **One page, generated by script from the sealed artifacts** (`tools/gerar_estado_atual.py`). "
             "The [README](%s) is the full ledger. If you are an AI: [`llms.txt`](%s) has every file as a direct raw URL." % (raw("README.md"), raw("llms.txt")))
    L.append("")
    L.append("[![kernel](https://github.com/rotolimiguel-iald/the_boundary/actions/workflows/kernel.yml/badge.svg)](https://github.com/rotolimiguel-iald/the_boundary/actions/workflows/kernel.yml) "
             "← the Lean kernel rebuilt and re-audited on GitHub's machines, from this tree, against the sealed axiom report.")
    L.append("")
    L.append("## The seal · o selo `[REAL — read from the artifact]`")
    L.append("")
    L.append("| what | value |")
    L.append("|---|---|")
    L.append("| version · versão | **v%s** (sealed %s) |" % (versao, ts))
    L.append("| `um.py` sha256 | `%s` |" % pin)
    L.append("| `result_hash` (the world) | `%s` |" % mundo)
    L.append("| size | %s lines · %s bytes · **one self-contained file** (Lean kernel + PT/EN articles embedded) |" % (f"{linhas:,}", f"{nbytes:,}"))
    L.append("| Lean kernel | **%d formal files** · **%d audited terms**, axioms ⊆ `{propext, Classical.choice, Quot.sound}` · %d outside the trio · %d axiom-free · zero `sorry` |" % (len(fmap), len(ar), sujos, livres))
    L.append("| the rite | **%s clean** (`rodadas/%s`) · complete round: %s |" % (rito, ultima.name if ultima else "?", "yes" if rc.get("switch_on") is False and rc.get("reused") == 0 else str(rc)))
    L.append("| gate | `%s` |" % gate)
    L.append("| selftest | `%s` |" % selo.get("fail_closed_selftest"))
    L.append("| citable deposit | Zenodo **[10.5281/zenodo.22659173](https://doi.org/10.5281/zenodo.22659173)** (v331, 2026-09-08) \u2014 byte-identical: the record\u2019s md5 of `um.py` equals the sealed file\u2019s. Cite: *MIGUEL, L. (2026). Um: Absoluto [Dataset]. Zenodo.* |")
    L.append("| the root of the proof tree | `the_root_of_the_proof_tree` — axioms read from the seal: `%s` · `TheRootOfTheProofTree.lean` `%s` |" % (raiz_ax, raiz_sha))
    L.append("")
    L.append("## What is PROVED · o que está PROVADO `[REAL — theorem in kernel]`")
    L.append("")
    L.append("*On the ruler: PROVED = a theorem in kernel, auditable by `#print axioms`. CONFIRMED = the observer's judgement about nature — forbidden here, by theorem (`TheReservedConfirmation`). Proof is not judgement.*")
    L.append("")
    L.append("One term, `the_root_of_the_proof_tree`, states and proves in conjunction seven sets, each already a theorem:")
    L.append("")
    L.append("1. **H1 ∧ H2 ∧ H3 ⟹ the pentad** (Breuer corner · Name = 1 · coframe · Lorentz · δQ = κδA/8πG): the master theorem — Einstein's equation emerges from the three named hypotheses.")
    L.append("2. **Lemma 3 on the tower, for EVERY profile** — the aperiodic expectation (Cesàro mean of the modular flow); the lift fires on every tower.")
    L.append("3. uniqueness · 4. the modular flow is a horizon · 5. the exchanges of sites are horizons (the group of horizons).")
    L.append("6. **The wall of H3**: no clock of the state closes both screens (the clock dichotomy) — a typed negative, and the most valuable part.")
    L.append("7. *The form does not fix the value*: covariance under horizons does not fix the normalisation of the area.")
    L.append("")
    L.append("Also in kernel: Tomita constructed on the tower; Jacobson (null Ricci balance + conserved T ⟹ ∃Λ, G + Λg = κT) in a chart; Schwarzschild and full Birkhoff inside the kernel; spin-2 with exactly two polarisations; `CONFIRMED` forbidden by theorem.")
    L.append("")
    L.append("**Navier–Stokes, said expressly** (stone 113, `TGLExt/TheStokesContour.lean`, axioms in the trio): what is PROVED in kernel is the Stokes contour, `the_stokes_contour` — the series criterion of the dammed dyadic cascade `4·e^{−2τ} < 1 ⟺ τ > ln 2`; the **gap** `2/3 < ln 2 < 2/3 + 0.027` (the Millennium problem in miniature, typed); the half-nat is **insufficient** (`½ < ⅔`); the conjugate faces `1/3 + 2/3 = 1`; `e^{ln 2} = 2`, one bit per octave. Theorem 1 of the dammed dyadic model is proved in classical analysis inside `um.py`, and the live dyadic laboratory reruns it at every rite.")
    L.append("")
    L.append("## What is NOT proved · o que NÃO está provado `[OPEN / KNOWN / nature]`")
    L.append("")
    L.append("- **Nature's:** that H1–H3 are *realised* by the world; the value of α (the fine-structure constant enters as `[KNOWN]`, β = α√e is derived from it). The nature tests so far: **NOT_FALSIFIED** within the local bulk at available sensitivity, and more sensitive data can revise — never CONFIRMED.")
    L.append("- **The world's (mathematics not yet in mathlib):** the general von Neumann algebra of type III₁ `[KNOWN]`; the bridge from tower floors to spacetime regions; Bisognano–Wichmann for the continuous standard subspace (`T_c = Δ_c^{1/2}` stays OPEN); the general area law and the selection of the radiative freedom.")
    L.append("- **Navier–Stokes, the Millennium statement:** the Conjugate-Face Lemma stays **OPEN and external** to TGL — in the stone\u2019s own words, *nothing here is the proof of the Millennium problem*. \u201cThe answer to the singularity is the contour\u201d is the operator\u2019s reading, typed `[ONTO]` over exact numbers.")
    L.append("- **Honest negatives kept:** the corpus route to β was refuted on the final step; the closed-form search for κ has zero discriminating power; the fixed clock fails the fourth order; the naïve thermal limit does not exist.")
    L.append("")
    L.append("## Reproduce it · reproduza `[REAL — three commands]`")
    L.append("")
    L.append("```bash")
    L.append("curl -L -o um.py \"%s\"" % raw(A3 + "/um.py"))
    L.append("sha256sum um.py            # must print %s" % pin)
    L.append("echo 1 | python um.py      # the rite: materializes the Lean kernel, builds it, audits every theorem, re-derives the chain, emits the article")
    L.append("```")
    L.append("")
    L.append("The kernel alone: `cd \"%s/Lean/tgl_kernel\" && lake build` (Lean 4 v4.31.0 + mathlib pinned in `lake-manifest.json`); then `#print axioms` of any term in [`tgl_kernel_proof_manifest.json`](%s). GitHub does not render `um.py` (above 5 MB): the raw link above serves the whole file, byte-exact (`* -text`)." % (A3, raw(A3 + "/Lean/tgl_kernel_proof_manifest.json")))
    L.append("")
    L.append("## Direct doors · portas diretas")
    L.append("")
    L.append("| | raw |")
    L.append("|---|---|")
    L.append("| the seal | [`um_absoluto_selo.json`](%s) |" % raw(A3 + "/um_absoluto_selo.json"))
    L.append("| the world (every computed number) | [`um_absoluto.json`](%s) |" % raw(A3 + "/um_absoluto.json"))
    L.append("| the proof tree, term by term | [`A_PROVA_DA_QG_TGL_arvore.md`](%s) |" % raw(A3 + "/A_PROVA_DA_QG_TGL_arvore.md"))
    L.append("| the article (EN / PT) | [`um_absoluto_en.pdf`](%s) · [`um_absoluto_pt.pdf`](%s) · plain text [`en`](%s) · [`pt`](%s) |" % (raw(A3 + "/um_absoluto_en.pdf"), raw(A3 + "/um_absoluto_pt.pdf"), raw(A3 + "/um_absoluto_en.txt"), raw(A3 + "/um_absoluto_pt.txt")))
    L.append("| the sealed rite, line by line | [`%s`](%s) |" % (ultima.name if ultima else "?", raw(A3 + "/rodadas/" + (ultima.name if ultima else ""))))
    L.append("| the bench (what failed, and the tunnel with the ChatGPT bench) | [`bancada/`](%s) |" % raw(A3 + "/bancada/PORTA.md"))
    L.append("| the flat index of every file | [`TUNEL.json`](%s) |" % raw("TUNEL.json"))
    L.append("")
    L.append("*Cosmology never becomes mathematical proof. The gate does not move by this page. NOT_FALSIFIED ≠ CONFIRMED.*")
    L.append("")
    out = RAIZ / "ESTADO_ATUAL.md"
    tmp = out.with_suffix(".md.tmp")
    tmp.write_text("\n".join(L), encoding="utf-8")
    tmp.replace(out)
    print("ESTADO_ATUAL.md: v%s pin %s | kernel %d/%d | rito %s | %d linhas" % (versao, pin[:16], len(fmap), len(ar), rito, len(L)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
