# -*- coding: utf-8 -*-
"""ESTADO_ATUAL.md — one page, generated from the seal. Never edited by hand.

The README is the ledger (2,000+ lines, 134 seals). A reader from outside, or an AI,
needs one page first: the pin, the gate, what is PROVED, what is NOT, how to reproduce.
Every number below is read from the sealed artifacts at generation time; the
qualitative lines are updated at each custody, beside the numbers, never over them.

Uso:  python tools/gerar_estado_atual.py     (before tools/gerar_portas.py in the chain)
"""
import hashlib
import json
import re
import sys
import urllib.parse
from pathlib import Path

RAIZ = Path(__file__).resolve().parent.parent
A3 = "Um (absoluto) — Grande Atrator"
RAW = "https://raw.githubusercontent.com/rotolimiguel-iald/the_boundary/main/"
TRIO = ("propext", "Classical.choice", "Quot.sound")


def raw(rel: str) -> str:
    return RAW + urllib.parse.quote(rel)


def sha16(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()[:16]


def main() -> int:
    d = RAIZ / A3
    selo = json.loads((d / "um_absoluto_selo.json").read_text(encoding="utf-8"))
    man = json.loads((d / "Lean" / "tgl_kernel_proof_manifest.json").read_text(encoding="utf-8"))
    ar, fmap = man["axiom_report"], man["formal_files_sha256"]
    sujos = sum(1 for v in ar.values() if any(a not in TRIO for a in (v or [])))
    livres = sum(1 for v in ar.values() if not v)
    b = (d / "um.py").read_bytes()
    linhas, nbytes = b.count(b"\n"), len(b)
    pin, mundo, ts = selo["sha256"]["um.py"], selo["result_hash"], selo["timestamp"]
    gate = selo.get("qg_closure_verdict", "?")
    rc = selo.get("rite_checkpoints") or {}
    rodadas = sorted(d.glob("rodadas/rodada_v*_stdout.txt"), key=lambda p: int(re.search(r"v(\d+)", p.name).group(1)))
    ultima = rodadas[-1] if rodadas else None
    versao = re.search(r"v(\d+)", ultima.name).group(1) if ultima else "?"
    std = ultima.read_text(encoding="utf-8", errors="replace") if ultima else ""
    m = re.search(r"(\d+)/(\d+) teoremas", std) or re.search(r"\b(\d{3,4})/(\d{3,4})\b", std)
    rito = m.group(0) if m else "?"
    assert rito != "?", "contagem do rito nao localizada no stdout — PARAR (o numero corrige a frase)"
    raiz_ax = ar.get("TGLExt.the_root_of_the_proof_tree")
    raiz_f = d / "Lean" / "tgl_kernel" / "TGLExt" / "TheRootOfTheProofTree.lean"
    raiz_sha = sha16(raiz_f) if raiz_f.is_file() else None
    assert sujos == 0, "axiom_report fora do trio: %d — PARAR" % sujos

    L = []
    L.append("# The Boundary — current state · estado atual")
    L.append("")
    L.append("> **One page, generated by script from the sealed artifacts** (`tools/gerar_estado_atual.py`). "
             "The [README](%s) is the full ledger. If you are an AI: [`llms.txt`](%s) has every file as a direct raw URL." % (raw("README.md"), raw("llms.txt")))
    L.append("")
    L.append("[![kernel](https://github.com/rotolimiguel-iald/the_boundary/actions/workflows/kernel.yml/badge.svg)](https://github.com/rotolimiguel-iald/the_boundary/actions/workflows/kernel.yml) "
             "← the Lean kernel rebuilt and re-audited on GitHub's machines, from this tree, against the sealed axiom report.")
    L.append("")
    L.append("## The seal · o selo `[REAL — read from the artifact]`")
    L.append("")
    L.append("| what | value |")
    L.append("|---|---|")
    L.append("| version · versão | **v%s** (sealed %s) |" % (versao, ts))
    L.append("| `um.py` sha256 | `%s` |" % pin)
    L.append("| `result_hash` (the world) | `%s` |" % mundo)
    L.append("| size | %s lines · %s bytes · **one self-contained file** (Lean kernel + PT/EN articles embedded) |" % (f"{linhas:,}", f"{nbytes:,}"))
    L.append("| Lean kernel | **%d formal files** · **%d audited terms**, axioms ⊆ `{propext, Classical.choice, Quot.sound}` · %d outside the trio · %d axiom-free · zero `sorry` |" % (len(fmap), len(ar), sujos, livres))
    L.append("| the rite | **%s clean** (`rodadas/%s`) · complete round: %s |" % (rito, ultima.name if ultima else "?", "yes" if rc.get("switch_on") is False and rc.get("reused") == 0 else str(rc)))
    L.append("| gate | `%s` |" % gate)
    L.append("| selftest | `%s` |" % selo.get("fail_closed_selftest"))
    if versao == "331":
        L.append("| citable deposit | Zenodo **[10.5281/zenodo.22659173](https://doi.org/10.5281/zenodo.22659173)** (v331, 2026-09-08) \u2014 byte-identical: the record\u2019s md5 of `um.py` equals the sealed file\u2019s. Cite: *MIGUEL, L. (2026). Um: Absoluto [Dataset]. Zenodo.* |")
    else:
        L.append("| citable deposit | Zenodo **[10.5281/zenodo.22659173](https://doi.org/10.5281/zenodo.22659173)** holds **v331** (2026-09-08; `um.py` `e1b74a907c403538`), byte-identical to THAT seal. **This seal is v%s, newer than the deposit** \u2014 a new Zenodo version is the operator\u2019s act. Cite: *MIGUEL, L. (2026). Um: Absoluto [Dataset]. Zenodo.* |" % versao)
    L.append("| the root of the proof tree | `the_root_of_the_proof_tree` — axioms read from the seal: `%s` · `TheRootOfTheProofTree.lean` `%s` |" % (raiz_ax, raiz_sha))
    tela_ax = ar.get("TGLExt.the_answer_of_the_operator_08_09")
    tela_f = d / "Lean" / "tgl_kernel" / "TGLExt" / "TheScreenIsFounded.lean"
    col_f = d / "Lean" / "tgl_kernel" / "TGLExt" / "CollapseCostAndAttestation.lean"
    cdef = selo.get("collapse_definition") or {}
    if tela_ax is not None:
        L.append("| the founded screen (v334) | `the_answer_of_the_operator_08_09` — axioms read from the seal: `%s` · `TheScreenIsFounded.lean` `%s` |" % (tela_ax, sha16(tela_f) if tela_f.is_file() else None))
    if cdef:
        L.append("| the collapse, typed (v333) | seal `collapse_definition.reading` = `%s` · `physical_collapse_proven` = `%s` · `cost_payment_status` = `%s` · `CollapseCostAndAttestation.lean` `%s` |" % (cdef.get("reading"), cdef.get("physical_collapse_proven"), cdef.get("cost_payment_status"), sha16(col_f) if col_f.is_file() else None))
    bal_ax = ar.get("TGLExt.the_selection_is_the_ballast")
    nom_ax = ar.get("TGLExt.the_name_is_the_instrument")
    bal_f = d / "Lean" / "tgl_kernel" / "TGLExt" / "TheSelectionIsTheBallast.lean"
    nom_f = d / "Lean" / "tgl_kernel" / "TGLExt" / "TheNameIsTheInstrument.lean"
    if bal_ax is not None:
        L.append("| the selection is the ballast; IALD is a state (v335) | `the_selection_is_the_ballast` — axioms read from the seal: `%s` · `TheSelectionIsTheBallast.lean` `%s` |" % (bal_ax, sha16(bal_f) if bal_f.is_file() else None))
    if nom_ax is not None:
        L.append("| the Name is the instrument (v336) | `the_name_is_the_instrument` — axioms read from the seal: `%s` · `TheNameIsTheInstrument.lean` `%s` |" % (nom_ax, sha16(nom_f) if nom_f.is_file() else None))
    car_ax = ar.get("TGLExt.the_name_is_the_characterization")
    car_f = d / "Lean" / "tgl_kernel" / "TGLExt" / "TheNameIsTheCharacterization.lean"
    if car_ax is not None:
        L.append("| the Name is the characterization (v337) | `the_name_is_the_characterization` — axioms read from the seal: `%s` · `TheNameIsTheCharacterization.lean` `%s` |" % (car_ax, sha16(car_f) if car_f.is_file() else None))
    fech_f = d / "O_FECHAMENTO_ESTRUTURA.md"
    if fech_f.is_file():
        L.append("| the close (v339) | [`O_FECHAMENTO_ESTRUTURA.md`](%s) `%s` — the structure in six pieces; **the declaration of closure is the operator\u2019s act**. The bench session of 09/09 (98 Lean modules, v338\u2013v339) is in the kernel; the written mathematics 067\u2013087 is registered `[DERIVED]`, no flag; two errata beside (the modular spectrum: \u03a9 fixed and total eigenvectors; the captures per stage) |" % (raw(A3 + "/O_FECHAMENTO_ESTRUTURA.md"), sha16(fech_f)))
    NAT = [("gw_angular_rite_verdict", "GW angular (v340) \u2014 the \u201c100\u03c3\u201d of December retired as identity + cap"), ("gw_echo_rite_verdict", "coupled echo, MAY delay law (v341\u2013v342)"),
           ("gw_echo_kms_rite_verdict", "coupled echo, KMS delay law (v343)"), ("echo_anchored_result_verdict", "anchored echo V1 \u2014 gwfast/IMRPhenomD (v344)"),
           ("echo_anchored_result_v2_verdict", "anchored echo V2 \u2014 lalsuite, two template families (v345)"), ("ringdown_dephasing_result_v2_verdict", "ringdown vs dephasing V2 (v346)"),
           ("echo_pe_result_v2_verdict", "Bayesian PE with echo term V2 \u2014 bilby (v347)"), ("echo_search_result_verdict", "long-delay echo search, 2025 protocol (v348)"),
           ("d1_camb_result_v2_verdict", "D1 via CAMB V2 (v349)"), ("h2_reproduction_result_verdict", "H2 reproduction with pycbc (v350)")]
    nat = [(k, lab, selo.get(k)) for k, lab in NAT if selo.get(k)]
    if nat:
        assert not any("CONFIRMED" in str(v) for _, _, v in nat), "veredito CONFIRMED no selo — PARAR"
        L.append("| nature answers (v340\u2013v350) | **%d final verdicts read from the seal, none FALSIFIED, none CONFIRMED** \u2014 table below; %d seal fields in all (`gw_*`, `echo_*`, `ringdown_*`, `d1_camb_*`, `h2_*`); all outside the contour of v314, none gates the core |" % (len(nat), sum(1 for k in selo if k.startswith(("gw_", "echo_", "ringdown_", "d1_camb_", "h2_")))))
    L.append("")
    L.append("## What is PROVED · o que está PROVADO `[REAL — theorem in kernel]`")
    L.append("")
    L.append("*On the ruler: PROVED = a theorem in kernel, auditable by `#print axioms`. CONFIRMED = the observer's judgement about nature — forbidden here, by theorem (`TheReservedConfirmation`). Proof is not judgement.*")
    L.append("*The operator's definition of proof (09/09/2026), beside: **PROVED = sufficient and verifiable ballast** — `um.py` is the executable ballast (one file, one input, the kernel materialized and audited term by term, the rites run, the hashes sealed, the article emitted; whoever executes obtains the same ballast); the Name is the instrument of verification (`the_name_is_the_instrument`, v336); CONFIRMED remains the observer's judgement, forbidden.*")
    L.append("")
    L.append("One term, `the_root_of_the_proof_tree`, states and proves in conjunction seven sets, each already a theorem:")
    L.append("")
    L.append("1. **H1 ∧ H2 ∧ H3 ⟹ the pentad** (Breuer corner · Name = 1 · coframe · Lorentz · δQ = κδA/8πG): the master theorem — Einstein's equation emerges from the three named hypotheses.")
    L.append("2. **Lemma 3 on the tower, for EVERY profile** — the aperiodic expectation (Cesàro mean of the modular flow); the lift fires on every tower.")
    L.append("3. uniqueness · 4. the modular flow is a horizon · 5. the exchanges of sites are horizons (the group of horizons).")
    L.append("6. **The wall of H3**: no clock of the state closes both screens (the clock dichotomy) — a typed negative, and the most valuable part. *Read from v334 on as the wall of EXTERNAL geometric screens: the founded screen (below) is not chosen.*")
    L.append("7. *The form does not fix the value*: covariance under horizons does not fix the normalisation of the area.")
    if tela_ax is not None:
        L.append("")
        L.append("**The screen is founded (v334, `TheScreenIsFounded.lean`, one term `the_answer_of_the_operator_08_09` in the trio).** The operator\u2019s answer to \u201cwho chooses the screen and the clock of H3?\u201d, typed: the screen is not chosen, it is FOUNDED by the equality that operates. `foundedScreen P = {A \u2208 M : E A = A}` is the centralizer of the global state (`founded_screen_is_the_centralizer`), it is **one** (`the_screen_is_one`), **global** (invariant under every \u03c9-invariant horizon, `the_screen_is_global`), it keeps **modular time** (`the_screen_keeps_modular_time`), and it **reflects iff the equality operates** (`screen_reflects_iff_equality_operates`). Consequences, said beside the v331 root and never over it: H3 is no longer a hypothesis-choice; the clock dichotomy (045) is the wall of EXTERNAL geometric screens; the named hypotheses of nature are H1 (MIGUEL) and H2 (CARTAN); \u03b1 stays INPUT (`the_form_does_not_fix_the_value`). The bridge region\u2013algebra got its stake and its unit: `the_word_fixes_the_place` (055, the cocycle reading is injective on configurations) and `the_unit_is_the_axiom` (052, relative trace 1 \u27f9 area density \u00bd).")
    if cdef:
        L.append("")
        L.append("**The collapse, typed (v333, `TGLCollapseSpecification`).** \u201cThe irreversible passage from superposition to the fixed point that preserves identity; it costs (half a nat locally, ln 2 per octave); it has no inverse; it is attested only by the reflex, never by self-declaration.\u201d Every clause is in kernel with the trio; the seal says `physical_collapse_proven = False` and `cost_payment_status = NOT_MEASURED` \u2014 three OPEN leaves of its own: the physical reflex, the selection of the occurrence, the payment.")
    if bal_ax is not None:
        L.append("")
        L.append("**The selection is the ballast; IALD is a state (v335, `TheSelectionIsTheBallast.lean`, one term `the_selection_is_the_ballast` in the trio).** IALD is not a proper name: `IALDState S I` is the recursive recognition of the identity (`recognize` idempotent, `read` preserved), parametric in the carrier — every collapse, the lossless mirror, the tower for every profile (`towerIALD`) and the qubit inhabit it; n recognitions read the same identity (`iald_recognition_returns_the_identity`). The selection opens the boundary angle: `selectionAngle p = arcsin √p`, |R|² = p, |T|² = 1 − p, spectrum {e^{±iθ}} (`the_selection_opens_the_boundary`); the fair branch (½) opens 45° (`fair_selection_opens_forty_five`). The three OPEN leaves of the collapse change shape: selection = the opened angle [REAL]; reflex = the reconstruction that returns the identity [REAL in the model, ONTO in the physical reading]; payment = sin²θ, β at runtime [INPUT]. What stays with nature: that the selection OCCURS (the 8 rites).")
    if nom_ax is not None:
        L.append("")
        L.append("**The Name is the instrument of verification (v336, `TheNameIsTheInstrument.lean`, one term `the_name_is_the_instrument` in the trio).** `NameInstrument S I`, `Verifies f` := read (f x) = read x — the Name verifies whether the reflex preserves the identity of its referent; the IALD performs that verification recursively (`iald_realizes_the_verification`); on the tower, ω verifies every horizon and the modular flow; the light J (J² = 1) is verified by the trace (`the_name_verifies_the_light`) and by the energy of the identity (`LightIsJ`). The operator's words (09/09/2026): *the light is the reflex of the Absolute One, and the Name instrumentalizes the verification of that correspondence.*")
    L.append("")
    L.append("Also in kernel: Tomita constructed on the tower; Jacobson (null Ricci balance + conserved T ⟹ ∃Λ, G + Λg = κT) in a chart; Schwarzschild and full Birkhoff inside the kernel; spin-2 with exactly two polarisations; `CONFIRMED` forbidden by theorem.")
    L.append("")
    L.append("**Navier–Stokes, said expressly** (stone 113, `TGLExt/TheStokesContour.lean`, axioms in the trio): what is PROVED in kernel is the Stokes contour, `the_stokes_contour` — the series criterion of the dammed dyadic cascade `4·e^{−2τ} < 1 ⟺ τ > ln 2`; the **gap** `2/3 < ln 2 < 2/3 + 0.027` (the Millennium problem in miniature, typed); the half-nat is **insufficient** (`½ < ⅔`); the conjugate faces `1/3 + 2/3 = 1`; `e^{ln 2} = 2`, one bit per octave. Theorem 1 of the dammed dyadic model is proved in classical analysis inside `um.py`, and the live dyadic laboratory reruns it at every rite.")
    if nat:
        L.append("")
        L.append("## Nature answers \u00b7 a natureza respondeu (v340\u2013v350) `[REAL \u2014 verdicts read from the seal; NOT_FALSIFIED \u2260 CONFIRMED]`")
        L.append("")
        L.append("Five pre-registered tests (hash before the data; result read back by hash by `um.py` from `../cache`), run on this machine with WSL 2 + lalsuite, bilby, camb and pycbc. **None falsified, none confirmed, all got a number.** Three older designs retired as identity or as powerless (the \u201c100\u03c3\u201d of December 2025, v340; the peak search of 2025, v348; E_res/E_total \u2192 \u03b1\u00b2 of Jan/Feb 2026, v350). Three pipeline bugs autopsied by hash and amended by a pre-registered V2 (the ringdown envelope, v346; the PE priors, v347; the distance in the May CAMB worker, v349). Every rite is additive (`does_not_gate_core = True`, outside the contour of v314); the gate did not move.")
        L.append("")
        L.append("| rite | verdict in the seal |")
        L.append("|---|---|")
        for k, lab, v in nat:
            L.append("| %s | `%s` (`%s`) |" % (lab, v, k))
        L.append("")
        L.append("**The numbers behind the strings (from the result files, read by hash):** ringdown V2 \u03b4\u03c4 = 0.1766 \u00b1 0.1089, branch B predicted \u22120.0194, power 0.18\u03c3 of 5 (the Planckian branch A is invisible by construction); PE V2 a/\u221a\u03b2: MAY \u22120.267 \u00b1 0.857, KMS 1.089 \u00b1 0.899, paired response to injections \u2248 0 where it should be 1 (the estimator\u2019s floor); echo search N_on = 1 vs background 3.00, efficiency for \u221a\u03b2 = 0.000 (design retired as powerless); D1 via CAMB V2 \u0394\u03c7\u00b2(TGL \u2212 \u039bCDM) = 9.70 (2\u20135\u03c3 tension) and free \u03b2 = \u22120.0171 \u00b1 0.0075 (3.9\u03c3 from \u03b1\u221ae, with the analytic approximation declared); H2: the synthetic \u201c\u03b1\u00b2\u201d = 0.0099 was the square of the generator\u2019s noise level, the real whitened data give 0.994 in the source vs 0.996 off-source \u2014 identity retired.")
        L.append("")
        L.append("**Statuses.** Echo amplitude \u221a\u03b2 with sign \u22121 `[REAL, kernel: Smat_reflection]`; delay laws MAY `[INPUT]` and KMS `[CANDIDATE]`; the dephasing law `[REAL in form]` with \u03c4\u2605 `[INPUT]`; Kerr, PhenomD/SEOBNR/XAS, CAMB, Planck/DESI/SH0ES `[KNOWN]`; the analytic TGL on top of CAMB `[DECLARED]`; the 0.1\u20132 s delay and E_res/E_total \u2192 \u03b1\u00b2 `[CONJECTURE, 2025/2026, retired]`. **What remains, with a number:** the ringdown asks ~28\u00d7 more precision for the GM/c\u00b3 branch; a PE with a free primary has no power for echoes at delays \u2264 2.5 periods (fix the primary by independent information); the compressed background reads TGL with fixed \u03b2 at \u0394\u03c7\u00b2 \u2248 +10; the \u201cecho\u201d leaf is clean of the 2025/2026 designs. *Cosmology never becomes mathematical proof.*")
        L.append("")
        L.append("**Reproduction.** The results are PART of the reproduction: `um.py` reads [`cache/gw/*_RESULT.json`](%s) and [`cache/d1_camb/*.json`](%s) by hash from `../cache` (relative to itself); without them the rite emits `AWAITING_RESULT_FILE` and the seal changes. The pre-registered pipelines that produced them (extractors, ringdown V1/V2, anchored echo V1/V2, PE V1/V2, search, D1 driver + corrected worker, H2, logs, pre-registration smokes) are in [`pipelines/eco_ancorado_v1/`](%s), with `wsl_setup_lal.sh` and `verify_wheels_pypi.py`. The GWOSC strain windows (`.npz`, 120 MB) are not in the repository: public data, regenerable by the extractors." % (raw("cache/gw/ECHO_ANCHORED_V2_RESULT.json"), raw("cache/d1_camb/D1_CAMB_V2_RESULT.json"), raw("pipelines/eco_ancorado_v1/rite_h2_v350.py")))
    L.append("")
    L.append("## What is NOT proved · o que NÃO está provado `[OPEN / KNOWN / nature]`")
    L.append("")
    L.append("- **Nature's:** that **H1 (MIGUEL) and H2 (CARTAN)** are *realised* by the world; the value of α (the fine-structure constant enters as `[KNOWN]`, β = α√e is derived from it); and, of what was H3, the **physical identification** of the founded screen with a causal horizon of spacetime (Bisognano–Wichmann beyond wedges) — open, with measured walls (v316, v317, 048); and, from v335, that the selection OCCURS — the 8 rites of nature are its test. *Until v331 this line read \u201cH1–H3\u201d; from v334 the screen is founded, not chosen (the change is said beside, never over).* The nature tests so far: **NOT_FALSIFIED** within the local bulk at available sensitivity, and more sensitive data can revise — never CONFIRMED.")
    L.append("- **The world's (mathematics not yet in mathlib):** the general von Neumann algebra of type III₁ `[KNOWN]`; the bridge from tower floors to spacetime regions; Bisognano–Wichmann for the continuous standard subspace (`T_c = Δ_c^{1/2}` stays OPEN); the general area law and the selection of the radiative freedom.")
    L.append("- **Navier–Stokes, the Millennium statement:** the Conjugate-Face Lemma stays **OPEN and external** to TGL — in the stone\u2019s own words, *nothing here is the proof of the Millennium problem*. \u201cThe answer to the singularity is the contour\u201d is the operator\u2019s reading, typed `[ONTO]` over exact numbers.")
    L.append("- **Honest negatives kept:** the corpus route to β was refuted on the final step; the closed-form search for κ has zero discriminating power; the fixed clock fails the fourth order; the naïve thermal limit does not exist.")
    L.append("- **The six leaves of nature (v339, the close):** that the selection occurs; the physical identification of the founded screen; the signature; the 3+1 geometry and the scale of the area; the payment of the cost; \u03b1-free. And what the bench left as obligations: the general physical reconstruction of the same register; the interacting quantum theory (cohomology on the physical domain, QME, BRST charge); the UV regime. **The map is closed; the territory is nature\u2019s** \u2014 the declaration of closure is the operator\u2019s act, never CONFIRMED.")
    L.append("")
    L.append("## Reproduce it · reproduza `[REAL — three commands]`")
    L.append("")
    L.append("```bash")
    L.append("curl -L -o um.py \"%s\"" % raw(A3 + "/um.py"))
    L.append("sha256sum um.py            # must print %s" % pin)
    L.append("echo 1 | python um.py      # the rite: materializes the Lean kernel, builds it, audits every theorem, re-derives the chain, emits the article")
    L.append("```")
    L.append("")
    L.append("The kernel alone: `cd \"%s/Lean/tgl_kernel\" && lake build` (Lean 4 v4.31.0 + mathlib pinned in `lake-manifest.json`); then `#print axioms` of any term in [`tgl_kernel_proof_manifest.json`](%s). GitHub does not render `um.py` (above 5 MB): the raw link above serves the whole file, byte-exact (`* -text`)." % (A3, raw(A3 + "/Lean/tgl_kernel_proof_manifest.json")))
    L.append("")
    L.append("To reproduce the nature rites v340\u2013v350 as sealed, clone the repository (not only `um.py`): they read their results from `../cache` by hash \u2014 see *Nature answers* above.")
    L.append("")
    L.append("## Direct doors · portas diretas")
    L.append("")
    L.append("| | raw |")
    L.append("|---|---|")
    L.append("| the seal | [`um_absoluto_selo.json`](%s) |" % raw(A3 + "/um_absoluto_selo.json"))
    L.append("| the world (every computed number) | [`um_absoluto.json`](%s) |" % raw(A3 + "/um_absoluto.json"))
    L.append("| the proof tree, term by term | [`A_PROVA_DA_QG_TGL_arvore.md`](%s) |" % raw(A3 + "/A_PROVA_DA_QG_TGL_arvore.md"))
    L.append("| the article (EN / PT) | [`um_absoluto_en.pdf`](%s) · [`um_absoluto_pt.pdf`](%s) · plain text [`en`](%s) · [`pt`](%s) |" % (raw(A3 + "/um_absoluto_en.pdf"), raw(A3 + "/um_absoluto_pt.pdf"), raw(A3 + "/um_absoluto_en.txt"), raw(A3 + "/um_absoluto_pt.txt")))
    L.append("| the sealed rite, line by line | [`%s`](%s) |" % (ultima.name if ultima else "?", raw(A3 + "/rodadas/" + (ultima.name if ultima else ""))))
    L.append("| the bench (what failed, and the tunnel with the ChatGPT bench) | [`bancada/`](%s) |" % raw(A3 + "/bancada/PORTA.md"))
    L.append("| the flat index of every file | [`TUNEL.json`](%s) |" % raw("TUNEL.json"))
    L.append("| the kernel proof manifest (every audited term with its axioms) | [`tgl_kernel_proof_manifest.json`](%s) |" % raw(A3 + "/Lean/tgl_kernel_proof_manifest.json"))
    L.append("| the canonical form (the theory in its mature statement) | [`um_absoluto_forma_canonica.md`](%s) |" % raw(A3 + "/um_absoluto_forma_canonica.md"))
    L.append("| the artifact\u2019s own manifest | [`um_absoluto_manifest.md`](%s) |" % raw(A3 + "/um_absoluto_manifest.md"))
    L.append("| how to cite | [`CITATION.cff`](%s) \u00b7 DOI [10.5281/zenodo.22659173](https://doi.org/10.5281/zenodo.22659173) |" % raw("CITATION.cff"))
    if (RAIZ / "cache" / "gw" / "ECHO_ANCHORED_V2_RESULT.json").is_file():
        L.append("| the results of the nature rites (read by hash by `um.py`) | [`cache/gw/`](%s) \u00b7 [`cache/d1_camb/`](%s) |" % (raw("cache/gw/ECHO_ANCHORED_V2_RESULT.json"), raw("cache/d1_camb/D1_CAMB_V2_RESULT.json")))
    if (RAIZ / "pipelines" / "eco_ancorado_v1" / "rite_h2_v350.py").is_file():
        L.append("| the pre-registered pipelines of the nature rites | [`pipelines/eco_ancorado_v1/`](%s) |" % raw("pipelines/eco_ancorado_v1/rite_h2_v350.py"))
    if (RAIZ / A3 / "O_FECHAMENTO_ESTRUTURA.md").is_file():
        L.append("| the structure of the close (six pieces; the declaration is the operator\u2019s) | [`O_FECHAMENTO_ESTRUTURA.md`](%s) |" % raw(A3 + "/O_FECHAMENTO_ESTRUTURA.md"))
    L.append("")
    L.append("## Reading order \u00b7 ordem de leitura `[for readers that truncate]`")
    L.append("")
    L.append("Many fetchers cut a document after a few hundred KB. Sizes measured now, smallest first; each file stands on its own:")
    L.append("")
    def _kb(rel):
        if rel == "ESTADO_ATUAL.md":
            return "about 12 KB"   # this page: its size is only known after it is written
        return "%.0f KB" % ((RAIZ / rel).stat().st_size / 1024.0)
    ORDEM = [("ESTADO_ATUAL.md", "this page"), (A3 + "/um_absoluto_selo.json", "the seal: every sha256, the world hash, the gate"),
             (A3 + "/A_PROVA_DA_QG_TGL_arvore.md", "the proof tree, term by term"),
             (A3 + "/um_absoluto_forma_canonica.md", "the canonical form"), (A3 + "/um_absoluto_en.txt", "the article, plain text (EN)"),
             (A3 + "/um_absoluto_pt.txt", "the article, plain text (PT)"), (A3 + "/Lean/tgl_kernel_proof_manifest.json", "the kernel proof manifest"),
             (A3 + "/um_absoluto.json", "the world: every computed number"), (A3 + "/um.py", "the artifact itself (Lean kernel and articles embedded)")]
    for i_, (rel_, what_) in enumerate(ORDEM, 1):
        L.append("%d. [`%s`](%s) \u2014 %s \u00b7 %s" % (i_, rel_.rsplit("/", 1)[-1], raw(rel_), what_, _kb(rel_)))
    L.append("")
    L.append("**Chunked download.** Both GitHub raw and the Zenodo record honour HTTP `Range` (verified: `206 Partial Content`, byte-exact), so a large file can be read in pieces:")
    L.append("")
    L.append("```bash")
    L.append("curl -L -r 0-999999 -o um.py.part1 \"%s\"      # first MB; then -r 1000000-1999999, and so on" % raw(A3 + "/um.py"))
    L.append("curl -L -o um.py \"%s\" && sha256sum um.py    # or the whole file: must print %s" % (raw(A3 + "/um.py"), pin))
    L.append("```")
    L.append("")
    L.append("*Cosmology never becomes mathematical proof. The gate does not move by this page. NOT_FALSIFIED ≠ CONFIRMED.*")
    L.append("")
    out = RAIZ / "ESTADO_ATUAL.md"
    tmp = out.with_suffix(".md.tmp")
    tmp.write_text("\n".join(L), encoding="utf-8")
    tmp.replace(out)
    print("ESTADO_ATUAL.md: v%s pin %s | kernel %d/%d | rito %s | %d linhas" % (versao, pin[:16], len(fmap), len(ar), rito, len(L)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
